(add-to-list 'load-path "~/.emacs.d/lisp/")
(require 'init-common)
(require 'init-font)
(require 'init-org-mode)
(require 'init-php-mode)
(require 'init-session)
(require 'init-slime)
(require 'init-theme)
