(add-to-list 'load-path "~/.emacs.d/lisp/")
(add-to-list 'load-path "~/.emacs.d/package/")
(require 'init-common)
(require 'init-font)
(require 'init-org-mode)
(require 'init-php-mode)
(require 'init-session)
(require 'init-slime)
(require 'init-theme)
(require 'init-auto-complete)
(require 'init-global-key)
(require 'init-windows)
(require 'init-autopair)
(require 'init-mark-multiple)
(require 'init-yasnippet)
(require 'init-web-mode)
(require 'init-cua-mode)
(require 'init-smex)
