;;; the following is only needed if you install org-page manually
(require 'org-page)
(setq op/repository-directory "~/work/swimmingwhale.github.io")
(setq op/site-domain "http://www.kuppobook.com/")
(setq op/site-main-title "木马牛")
(setq op/site-sub-title "等咱有了钱，买两碗豆浆，一碗爱喝不喝，一碗就是不喝！")
(setq op/personal-github-link "https://github.com/swimmingwhale")
(setq op/personal-disqus-shortname "swimmingwhale")
(setq op/personal-google-analytics-id "your_google_analytics_id")
(setq op/theme 'mmn)
(provide 'init-org-page)
